import { Injectable, UnauthorizedException, ConflictException, NotFoundException } from '@nestjs/common';
import { UsersService } from '../users/users.service';
import { JwtService } from '@nestjs/jwt';
import * as bcrypt from 'bcryptjs';
import * as crypto from 'crypto';
import { InjectRepository } from '@nestjs/typeorm';
import { AccountEntity } from '../account/account.entity';
import { Repository } from 'typeorm';
import { UserEntity } from '../users/user.entity';
import { CACHE_MANAGER } from '@nestjs/cache-manager';
import { Inject, BadRequestException } from '@nestjs/common';
import { InjectQueue } from '@nestjs/bull';
import { Queue } from 'bull';
import { PlanPermissionService } from '../payment/plan-permission.service';
import { NotificationsService } from '../notifications/notifications.service';
import { SmsService } from '../notifications/sms.service';
import { SmsTemplates } from '../notifications/sms-templates';
import { AuditLogService } from './audit-log.service';
import { generateSecret, generateURI, verifySync } from 'otplib';
import * as qrcode from 'qrcode';

@Injectable()
export class AuthService {
    constructor(
        private usersService: UsersService,
        private jwtService: JwtService,
        @InjectRepository(AccountEntity)
        private accountRepository: Repository<AccountEntity>,
        @InjectQueue('email-queue') private emailQueue: Queue,
        @Inject(CACHE_MANAGER) private cacheManager: any,
        private planPermissionService: PlanPermissionService,
        private smsService: SmsService,
        private notificationsService: NotificationsService,
        private auditLogService: AuditLogService,
    ) { }

    async validateUser(email: string, pass: string): Promise<any> {
        const user = await this.usersService.findOneByEmail(email);
        if (user && (await bcrypt.compare(pass, user.passwordHash))) {
            const { passwordHash, ...result } = user;
            return result;
        }
        return null;
    }

    async login(user: any, ip?: string, userAgent?: string) {
        // Auto-fix: Ensure user has API Token
        let updated = false;
        if (!user.apiToken) {
            user.apiToken = crypto.randomUUID().toUpperCase();
            updated = true;
        }

        // Check if account exists, create if not (Legacy parity)
        const existingAccount = await this.accountRepository.findOne({ where: { userId: user.id } });
        if (!existingAccount) {
            await this.createDefaultAccount(user.id);
        }

        if (updated) {
            await this.usersService.update(user);
        }

        // --- 2FA INTERCEPTION ---
        // New: Check for TOTP (Google Authenticator)
        if (user.twoFactorEnabled && user.isTwoFactorConfirmed) {
            await this.auditLogService.log(user.id, 'LOGIN_2FA_REQUIRED', { ip, userAgent }, ip, userAgent);
            
            // Proactively send code via WhatsApp if linked (as backup/convenience)
            // Note: TOTP code is generated by app, but we can send a parallel OTP to WhatsApp
            // to fulfill the user's request that "any of the two codes will be valid"
            const otp = Math.floor(100000 + Math.random() * 900000).toString();
            await this.cacheManager.set(`2FA:${user.id}`, otp, 300000); // 5 mins
            
            // Dispatch WhatsApp 2FA if linked
            await this.notificationsService.send2FA(user.id, otp).catch(() => {});
            
            return {
                success: true,
                twoFactorRequired: true,
                twoFactorType: 'TOTP',
                userId: user.id,
                email: user.email,
                hasWhatsAppBackup: true
            };
        }

        // Legacy: Email 2FA (if enabled but TOTP not set/confirmed)
        if (user.twoFactorEnabled) {
            const otp = Math.floor(100000 + Math.random() * 900000).toString();
            await this.cacheManager.set(`2FA:${user.id}`, otp, 300000);

            await this.emailQueue.add('otp-alert', {
                email: user.email,
                otp
            }, { removeOnComplete: true });

            // Also try WhatsApp if enabled
            await this.notificationsService.send2FA(user.id, otp).catch(() => {});

            await this.auditLogService.log(user.id, 'LOGIN_2FA_REQUIRED_EMAIL', { ip, userAgent }, ip, userAgent);
            return {
                success: true,
                twoFactorRequired: true,
                twoFactorType: 'EMAIL',
                userId: user.id,
                email: user.email
            };
        }

        return this.generateAuthResponse(user, ip, userAgent);
    }

    private async generateAuthResponse(user: any, ip?: string, userAgent?: string) {
        const payload = { email: user.email, id: user.id };
        const accessToken = this.jwtService.sign(payload);
        const refreshToken = crypto.randomUUID();

        // Store refresh token
        await this.usersService.updateRefreshToken(user.id, refreshToken);

        await this.auditLogService.log(user.id, 'LOGIN_SUCCESS', { ip, userAgent }, ip, userAgent);

        // Dispatch Login Alert (Async)
        await this.emailQueue.add('login-alert', {
            email: user.email,
            name: user.name,
            ip: ip || 'Unknown IP',
            device: userAgent || 'Unknown Device',
            time: new Date().toLocaleString('pt-BR', { timeZone: 'Africa/Maputo' })
        }, { removeOnComplete: true });

        const planTier = await this.planPermissionService.getUserPlan(user.id);

        return {
            success: true,
            message: 'Login successful',
            token: accessToken,
            refreshToken,
            user: {
                id: user.id,
                name: user.name,
                email: user.email,
                api_token: user.apiToken,
                tier: planTier,
                onboardingCompleted: user.onboardingCompleted
            }
        };
    }

    async refresh(refreshToken: string, ip?: string, userAgent?: string) {
        const user = await this.usersService.findOneByRefreshToken(refreshToken);
        if (!user) {
            await this.auditLogService.log(null, 'REFRESH_TOKEN_INVALID', { refreshToken, ip, userAgent }, ip, userAgent);
            throw new UnauthorizedException('Token de atualização inválido');
        }

        await this.auditLogService.log(user.id, 'REFRESH_TOKEN_SUCCESS', { ip, userAgent }, ip, userAgent);
        return this.generateAuthResponse(user, ip, userAgent);
    }

    async sendOtp(email: string) {
        if (await this.usersService.findOneByEmail(email)) {
            throw new ConflictException('Email already registered');
        }

        const otp = Math.floor(100000 + Math.random() * 900000).toString();
        // 10 minutes = 600000 ms (or seconds depending on version, cache-manager v5 uses ms)
        await this.cacheManager.set(`OTP:${email}`, otp, 600000);

        await this.emailQueue.add('otp-alert', {
            email,
            otp
        }, { removeOnComplete: true });

        return { success: true, message: 'OTP sent successfully' };
    }

    async register(data: any) {
        if (!data.otp) {
            throw new BadRequestException('OTP is required');
        }

        const storedOtp = await this.cacheManager.get(`OTP:${data.email}`);
        if (!storedOtp || storedOtp !== data.otp) {
            throw new BadRequestException('Invalid or expired OTP');
        }

        if (await this.usersService.findOneByEmail(data.email)) {
            throw new ConflictException('Email already registered');
        }

        // Delete OTP after usage
        await this.cacheManager.del(`OTP:${data.email}`);

        const salt = await bcrypt.genSalt(10);
        const passwordHash = await bcrypt.hash(data.password, salt);

        const newUser = await this.usersService.create({
            name: data.name,
            email: data.email,
            passwordHash: passwordHash,
            whatsapp: data.contact || data.whatsapp,
            apiToken: crypto.randomUUID().toUpperCase()
        });

        await this.auditLogService.log(newUser.id, 'USER_REGISTERED', { email: newUser.email });

        // Create default Account
        await this.createDefaultAccount(newUser.id);

        // Dispatch Welcome Email
        await this.emailQueue.add('welcome', {
            email: newUser.email,
            name: newUser.name
        }, { removeOnComplete: true });

        // Dispatch Welcome SMS (Systemic)
        if (newUser.whatsapp) {
            await this.smsService.sendSms(
                newUser.id, 
                newUser.whatsapp, 
                SmsTemplates.WELCOME(newUser.name),
                true // isSystemic
            );
        }

        const payload = { email: newUser.email, id: newUser.id };
        const planTier = await this.planPermissionService.getUserPlan(newUser.id);

        return {
            success: true,
            message: 'User registered successfully',
            token: this.jwtService.sign(payload),
            user: {
                id: newUser.id,
                name: newUser.name,
                email: newUser.email,
                api_token: newUser.apiToken,
                tier: planTier,
                onboardingCompleted: false
            }
        };
    }

    async forgotPassword(email: string) {
        const user = await this.usersService.findOneByEmail(email);
        if (!user) {
            await this.auditLogService.log(null, 'FORGOT_PASSWORD_FAILED', { email });
            throw new BadRequestException('Email not found');
        }

        await this.auditLogService.log(user.id, 'FORGOT_PASSWORD_REQUESTED', { email });

        const otp = Math.floor(100000 + Math.random() * 900000).toString();
        // 10 minutes
        await this.cacheManager.set(`OTP:${email}`, otp, 600000);

        // Reuse otp-alert (generic enough: "Seu Código de Verificação")
        await this.emailQueue.add('otp-alert', {
            email,
            otp
        }, { removeOnComplete: true });

        return { success: true, message: 'OTP sent to your email' };
    }

    async resetPassword(data: any) {
        const { email, otp, newPassword } = data;

        if (!email || !otp || !newPassword) {
            throw new BadRequestException('Missing required fields');
        }

        const storedOtp = await this.cacheManager.get(`OTP:${email}`);
        if (!storedOtp || storedOtp !== otp) {
            throw new BadRequestException('Invalid or expired OTP');
        }

        const user = await this.usersService.findOneByEmail(email);
        if (!user) {
            throw new BadRequestException('User not found');
        }

        // Delete OTP
        await this.cacheManager.del(`OTP:${email}`);

        // Update Password
        const salt = await bcrypt.genSalt(10);
        user.passwordHash = await bcrypt.hash(newPassword, salt);

        await this.usersService.update(user); 

        await this.auditLogService.log(user.id, 'PASSWORD_RESET_SUCCESS', { email });

        return { success: true, message: 'Password updated successfully' };
    }

    async regenerateToken(userId: string) {
        const user = await this.usersService.findOneById(userId);
        if (!user) throw new UnauthorizedException();

        const newToken = crypto.randomUUID().toUpperCase();
        user.apiToken = newToken;
        await this.usersService.update(user);

        // Sync with AccountEntity
        const account = await this.accountRepository.findOne({ where: { userId } });
        if (account) {
            account.appToken = newToken;
            await this.accountRepository.save(account);
        } else {
            // Should verify if we need to create one, but for now just sync if exists is fine
            // Or better, create one to be safe if missing
            await this.createDefaultAccount(userId, newToken);
        }

        return {
            success: true,
            message: 'Token regenerated successfully',
            api_token: user.apiToken
        }
    }

    async validateGoogleUser(profile: any) {
        let user = await this.usersService.findOneByGoogleId(profile.googleId);

        if (!user) {
            user = await this.usersService.findOneByEmail(profile.email);
            if (user) {
                // Link Google to existing account
                user.googleId = profile.googleId;
                await this.usersService.update(user);
            } else {
                // Create new social account
                user = await this.usersService.create({
                    email: profile.email,
                    name: profile.name,
                    googleId: profile.googleId,
                    avatarUrl: profile.avatarUrl,
                    apiToken: crypto.randomUUID().toUpperCase(),
                });
                await this.createDefaultAccount(user.id);
            }
        }

        const payload = { email: user.email, id: user.id };
        const token = this.jwtService.sign(payload);

        return {
            success: true,
            token,
            user: {
                id: user.id,
                name: user.name,
                email: user.email,
                api_token: user.apiToken,
                onboardingCompleted: user.onboardingCompleted
            },
            requiresContact: !user.whatsapp
        };
    }

    async validateGithubUser(profile: any) {
        let user = await this.usersService.findOneByGithubId(profile.githubId);

        if (!user) {
            user = await this.usersService.findOneByEmail(profile.email);
            if (user) {
                // Link Github to existing account
                user.githubId = profile.githubId;
                await this.usersService.update(user);
            } else {
                // Create new social account
                user = await this.usersService.create({
                    email: profile.email,
                    name: profile.name,
                    githubId: profile.githubId,
                    avatarUrl: profile.avatarUrl,
                    apiToken: crypto.randomUUID().toUpperCase(),
                });
                await this.createDefaultAccount(user.id);
            }
        }

        const payload = { email: user.email, id: user.id };
        const token = this.jwtService.sign(payload);

        return {
            success: true,
            token,
            user: {
                id: user.id,
                name: user.name,
                email: user.email,
                api_token: user.apiToken,
                onboardingCompleted: user.onboardingCompleted
            },
            requiresContact: !user.whatsapp
        };
    }

    async getAppToken(userId: string) {
        let account = await this.accountRepository.findOne({ where: { userId } });

        if (!account) {
            account = await this.createDefaultAccount(userId);
        }

        if (!account.appToken) {
            account.appToken = crypto.randomUUID().toUpperCase();
            await this.accountRepository.save(account);
        }

        return { token: account.appToken };
    }

    async setupTwoFactor(userId: string) {
        const user = await this.usersService.findOneById(userId);
        if (!user) throw new NotFoundException('Usuário não encontrado');

        const secret = generateSecret();
        const otpauthUrl = generateURI({
            label: user.email,
            issuer: 'Torex Journal',
            secret
        });
        const qrCodeDataUrl = await qrcode.toDataURL(otpauthUrl);

        // Store secret temporarily but don't confirm yet
        user.twoFactorSecret = secret;
        user.isTwoFactorConfirmed = false;
        await this.usersService.update(user);

        return {
            secret,
            qrCodeDataUrl
        };
    }

    async verifyTwoFactorSetup(userId: string, token: string) {
        const user = await this.usersService.findOneById(userId);
        if (!user || !user.twoFactorSecret) {
            throw new BadRequestException('Setup de 2FA não iniciado');
        }

        const isValid = verifySync({
            token,
            secret: user.twoFactorSecret
        }).valid;

        if (!isValid) {
            throw new BadRequestException('Código 2FA inválido');
        }

        user.isTwoFactorConfirmed = true;
        user.twoFactorEnabled = true;
        await this.usersService.update(user);

        await this.auditLogService.log(userId, '2FA_SETUP_SUCCESS', { type: 'TOTP' });

        return { success: true };
    }

    async verify2fa(userId: string, otp: string, ip?: string, userAgent?: string) {
        const user = await this.usersService.findOneById(userId);
        if (!user) throw new BadRequestException('Usuário não encontrado');

        // Try Cached OTP first (WhatsApp/Email backup)
        const storedOtp = await this.cacheManager.get(`2FA:${userId}`);
        if (storedOtp && storedOtp === otp) {
            await this.cacheManager.del(`2FA:${userId}`);
            await this.auditLogService.log(userId, '2FA_VERIFICATION_SUCCESS', { type: 'BACKUP_OTP', ip, userAgent }, ip, userAgent);
            return this.generateAuthResponse(user, ip, userAgent);
        }

        // Check for TOTP if backup OTP didn't match or exist
        if (user.isTwoFactorConfirmed && user.twoFactorSecret) {
            const isValid = verifySync({
                token: otp,
                secret: user.twoFactorSecret
            }).valid;
            
            if (isValid) {
                await this.auditLogService.log(userId, '2FA_VERIFICATION_SUCCESS', { type: 'TOTP', ip, userAgent }, ip, userAgent);
                return this.generateAuthResponse(user, ip, userAgent);
            }
        }

        await this.auditLogService.log(userId, '2FA_VERIFICATION_FAILED', { ip, userAgent }, ip, userAgent);
        throw new BadRequestException('Código 2FA inválido ou expirado');
    }

    async saveOnboardingSurvey(userId: string, surveyData: any) {
        const user = await this.usersService.findOneById(userId);
        if (!user) throw new NotFoundException('Usuário não encontrado');

        user.surveyAnswers = surveyData;
        user.onboardingCompleted = true;
        await this.usersService.update(user);

        return { success: true, onboardingCompleted: true };
    }

    async setTwoFactor(userId: string, enabled: boolean) {
        const user = await this.usersService.findOneById(userId);
        if (!user) throw new NotFoundException('Usuário não encontrado');

        user.twoFactorEnabled = enabled;
        await this.usersService.update(user);

        return { success: true, enabled: user.twoFactorEnabled };
    }

    private async createDefaultAccount(userId: string, forcedToken?: string) {
        const user = await this.usersService.findOneById(userId);
        const token = forcedToken || (user ? user.apiToken : crypto.randomUUID().toUpperCase());

        const account = this.accountRepository.create({
            userId: userId,
            appToken: token,
            mt5Id: null,
            balance: 0,
            equity: 0,
            isConnected: false
        });
        return this.accountRepository.save(account);
    }
}
