import { Injectable, Logger, OnModuleInit } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { EventEmitter2 } from '@nestjs/event-emitter';
import axios from 'axios';

@Injectable()
export class BaileysService implements OnModuleInit {
    private readonly logger = new Logger(BaileysService.name);
    private state: string = 'close';
    public qrCode: string | null = null;
    private isPolling = false;

    private apiUrl: string;
    private apiKey: string;
    private instanceName: string;
    private baseUrl: string;

    constructor(
        private configService: ConfigService,
        private eventEmitter: EventEmitter2
    ) {
        this.apiUrl = this.configService.get<string>('EVOLUTION_API_URL') || 'https://wa.ratixpay.co.mz';
        this.apiKey = this.configService.get<string>('EVOLUTION_API_KEY') || 'ratixpay_secret_key_2026';
        this.instanceName = this.configService.get<string>('EVOLUTION_API_INSTANCE_NAME') || 'torex_journal';
        this.baseUrl = this.configService.get<string>('BASE_URL') || 'http://localhost:3000';
    }

    async onModuleInit() {
        this.logger.log('Initializing BaileysService with Evolution API');
        // Do not block startup, poll in background
        this.isPolling = true;
        this.startStatusPolling();
        this.configureWebhook().catch(err => {
            this.logger.error(`Failed to configure Evolution API Webhook: ${err.message}`);
        });
    }

    private startStatusPolling() {
        const poll = async () => {
            if (!this.isPolling) return;
            try {
                const response = await axios.get(
                    `${this.apiUrl}/instance/connectionState/${this.instanceName}`,
                    { headers: { apikey: this.apiKey }, timeout: 10000 }
                );
                
                const remoteState = response.data?.instance?.state || 'close';
                
                // Map status to what controllers expect ('open' | 'close' | 'connecting')
                if (remoteState === 'open') {
                    if (this.state !== 'open') {
                        this.logger.log('WhatsApp instance is open/connected.');
                        this.eventEmitter.emit('whatsapp.connected');
                    }
                    this.state = 'open';
                    this.qrCode = null;
                } else {
                    this.state = 'close';
                    // If not open, fetch QR code to present it on the status dashboard
                    await this.fetchQrCode();
                }
            } catch (error: any) {
                const status = error.response?.status;
                if (status === 404) {
                    this.logger.warn(`WhatsApp instance '${this.instanceName}' not found (404) on Evolution API. Stopping background status checks.`);
                } else {
                    this.logger.warn(`Error polling connection status: ${error.message}. Stopping background status checks.`);
                }
                this.state = 'close';
                this.isPolling = false;
                return;
            }

            if (this.isPolling) {
                // Poll every 30 seconds
                setTimeout(poll, 30000);
            }
        };
        
        poll();
    }

    private async fetchQrCode() {
        try {
            const response = await axios.get(
                `${this.apiUrl}/instance/connect/${this.instanceName}`,
                { headers: { apikey: this.apiKey }, timeout: 15000 }
            );

            const code = response.data?.code || response.data?.qrcode?.code || response.data?.pairingCode;
            if (code && code !== this.qrCode) {
                this.qrCode = code;
                this.logger.warn('New WhatsApp QR Code generated by Evolution API.');
                this.eventEmitter.emit('whatsapp.qr', code);
            }
        } catch (error) {
            // Silence connection failures if instance is already in a weird state
            this.logger.debug(`Could not fetch QR code: ${error.message}`);
        }
    }

    private async configureWebhook() {
        if (!this.baseUrl || this.baseUrl.includes('localhost')) {
            this.logger.warn(`Local environment detected (${this.baseUrl}). Webhook auto-configuration skipped.`);
            return;
        }

        try {
            const webhookUrl = `${this.baseUrl}/api/whatsapp/webhook`;
            this.logger.log(`Registering Evolution API webhook to: ${webhookUrl}`);
            await axios.post(
                `${this.apiUrl}/webhook/set/${this.instanceName}`,
                {
                    enabled: true,
                    url: webhookUrl,
                    webhookByEvents: false,
                    webhookBase64: false,
                    events: [
                        'MESSAGES_UPSERT',
                        'CONNECTION_UPDATE'
                    ]
                },
                { headers: { apikey: this.apiKey }, timeout: 15000 }
            );
            this.logger.log('Evolution API webhook registered successfully.');
        } catch (error) {
            this.logger.error(`Failed to set webhook: ${error.message}`);
        }
    }

    async sendMessage(number: string, text: string): Promise<boolean> {
        // Remove @s.whatsapp.net if present to pass clean number to Evolution API
        let formattedNumber = number;
        if (formattedNumber.includes('@')) {
            formattedNumber = formattedNumber.split('@')[0];
        }

        this.logger.log(`Sending message via Evolution API to: ${formattedNumber}`);
        try {
            await axios.post(
                `${this.apiUrl}/message/sendText/${this.instanceName}`,
                {
                    number: formattedNumber,
                    text: text
                },
                { headers: { apikey: this.apiKey }, timeout: 15000 }
            );
            return true;
        } catch (error) {
            this.logger.error(`Failed to send message to ${formattedNumber}: ${error.message}`);
            return false;
        }
    }

    getConnectionStatus(): string {
        if (!this.isPolling) {
            this.logger.log('Resuming WhatsApp status polling...');
            this.isPolling = true;
            this.startStatusPolling();
        }
        return this.state;
    }

    async logout(): Promise<boolean> {
        this.logger.log('Logging out from WhatsApp instance...');
        try {
            await axios.post(
                `${this.apiUrl}/instance/logout/${this.instanceName}`,
                {},
                { headers: { apikey: this.apiKey }, timeout: 15000 }
            );
            this.state = 'close';
            this.qrCode = null;
            return true;
        } catch (error) {
            this.logger.error(`Failed to logout: ${error.message}`);
            return false;
        }
    }
}

