import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchemaLoose1769260033286 implements MigrationInterface {
    name = 'InitialSchemaLoose1769260033286'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "accounts" DROP CONSTRAINT "accounts_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "trades" DROP CONSTRAINT "trades_account_id_fkey"`);
        await queryRunner.query(`DROP INDEX "public"."trades_account_id_ticket"`);
        await queryRunner.query(`DROP INDEX "public"."trades_account_id_close_time"`);
        await queryRunner.query(`CREATE TABLE "positions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "account_id" uuid NOT NULL, "ticket" bigint NOT NULL, "symbol" character varying NOT NULL, "type" character varying NOT NULL, "volume" numeric(10,2) NOT NULL, "open_price" numeric(10,5) NOT NULL, "current_price" numeric(10,5), "profit" numeric(10,2) NOT NULL, "sl" numeric(10,5), "tp" numeric(10,5), "open_time" TIMESTAMP NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_17e4e62ccd5749b289ae3fae6f3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "trades" ADD "commission" numeric(10,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "trades" ADD "swap" numeric(10,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "accounts" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "accounts" DROP CONSTRAINT "accounts_mt5_id_key15"`);
        await queryRunner.query(`ALTER TABLE "accounts" DROP COLUMN "mt5_id"`);
        await queryRunner.query(`ALTER TABLE "accounts" ADD "mt5_id" character varying`);
        await queryRunner.query(`ALTER TABLE "accounts" ADD CONSTRAINT "UQ_bcf86751360dd18bab5efab623a" UNIQUE ("mt5_id")`);
        await queryRunner.query(`ALTER TABLE "accounts" ALTER COLUMN "balance" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "accounts" ALTER COLUMN "equity" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "accounts" ALTER COLUMN "margin" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "accounts" ALTER COLUMN "margin_free" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "accounts" ALTER COLUMN "margin_level" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "accounts" ALTER COLUMN "leverage" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "accounts" ALTER COLUMN "is_connected" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "accounts" DROP COLUMN "last_seen"`);
        await queryRunner.query(`ALTER TABLE "accounts" ADD "last_seen" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "accounts" DROP CONSTRAINT "accounts_app_token_key15"`);
        await queryRunner.query(`ALTER TABLE "accounts" DROP COLUMN "app_token"`);
        await queryRunner.query(`ALTER TABLE "accounts" ADD "app_token" character varying`);
        await queryRunner.query(`ALTER TABLE "accounts" ADD CONSTRAINT "UQ_18a4c67cb67bb420271d415b5e1" UNIQUE ("app_token")`);
        await queryRunner.query(`ALTER TABLE "accounts" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "accounts" ADD "user_id" character varying`);
        await queryRunner.query(`ALTER TABLE "accounts" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "accounts" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "accounts" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "accounts" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "trades" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "trades" DROP COLUMN "account_id"`);
        await queryRunner.query(`ALTER TABLE "trades" ADD "account_id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "trades" DROP COLUMN "symbol"`);
        await queryRunner.query(`ALTER TABLE "trades" ADD "symbol" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "trades" DROP COLUMN "type"`);
        await queryRunner.query(`ALTER TABLE "trades" ADD "type" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "trades" ALTER COLUMN "open_price" TYPE numeric(10,5)`);
        await queryRunner.query(`ALTER TABLE "trades" ALTER COLUMN "close_price" TYPE numeric(10,5)`);
        await queryRunner.query(`ALTER TABLE "trades" ALTER COLUMN "close_price" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "trades" ALTER COLUMN "profit" TYPE numeric(10,2)`);
        await queryRunner.query(`ALTER TABLE "trades" ALTER COLUMN "profit" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "trades" DROP COLUMN "open_time"`);
        await queryRunner.query(`ALTER TABLE "trades" ADD "open_time" TIMESTAMP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "trades" DROP COLUMN "close_time"`);
        await queryRunner.query(`ALTER TABLE "trades" ADD "close_time" TIMESTAMP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "trades" DROP COLUMN "status"`);
        await queryRunner.query(`DROP TYPE "public"."enum_trades_status"`);
        await queryRunner.query(`ALTER TABLE "trades" ADD "status" character varying NOT NULL DEFAULT 'CLOSED'`);
        await queryRunner.query(`ALTER TABLE "trades" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "trades" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "trades" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "trades" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "name" character varying`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "users_email_key15"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "email" character varying`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email")`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "password_hash"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "password_hash" character varying`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "whatsapp"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "whatsapp" character varying`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "users_api_token_key15"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "api_token"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "api_token" character varying`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "UQ_b0c7bff7a2c2f7f12d3a90b4f33" UNIQUE ("api_token")`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "email" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "nomeCliente"`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "nomeCliente" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "produto"`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "produto" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "status" character varying NOT NULL DEFAULT 'aprovada'`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "payments_vendaId_key12"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "vendaId"`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "vendaId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "UQ_dc2128d1b02348c38c156f03695" UNIQUE ("vendaId")`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "dataHora"`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "dataHora" TIMESTAMP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "positions" ADD CONSTRAINT "FK_0ed8ab557a8fb4125b8948bd79b" FOREIGN KEY ("account_id") REFERENCES "accounts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "positions" DROP CONSTRAINT "FK_0ed8ab557a8fb4125b8948bd79b"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "dataHora"`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "dataHora" TIMESTAMP WITH TIME ZONE NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "UQ_dc2128d1b02348c38c156f03695"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "vendaId"`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "vendaId" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "payments_vendaId_key12" UNIQUE ("vendaId")`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "status" character varying(255) NOT NULL DEFAULT 'aprovada'`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "produto"`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "produto" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "nomeCliente"`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "nomeCliente" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "email" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "UQ_b0c7bff7a2c2f7f12d3a90b4f33"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "api_token"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "api_token" uuid`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "users_api_token_key15" UNIQUE ("api_token")`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "whatsapp"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "whatsapp" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "password_hash"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "password_hash" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "email" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "users_email_key15" UNIQUE ("email")`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "name" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "trades" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "trades" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL`);
        await queryRunner.query(`ALTER TABLE "trades" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "trades" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL`);
        await queryRunner.query(`ALTER TABLE "trades" DROP COLUMN "status"`);
        await queryRunner.query(`CREATE TYPE "public"."enum_trades_status" AS ENUM('OPEN', 'CLOSED')`);
        await queryRunner.query(`ALTER TABLE "trades" ADD "status" "public"."enum_trades_status" DEFAULT 'OPEN'`);
        await queryRunner.query(`ALTER TABLE "trades" DROP COLUMN "close_time"`);
        await queryRunner.query(`ALTER TABLE "trades" ADD "close_time" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "trades" DROP COLUMN "open_time"`);
        await queryRunner.query(`ALTER TABLE "trades" ADD "open_time" TIMESTAMP WITH TIME ZONE NOT NULL`);
        await queryRunner.query(`ALTER TABLE "trades" ALTER COLUMN "profit" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "trades" ALTER COLUMN "profit" TYPE numeric(15,2)`);
        await queryRunner.query(`ALTER TABLE "trades" ALTER COLUMN "close_price" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "trades" ALTER COLUMN "close_price" TYPE numeric(15,5)`);
        await queryRunner.query(`ALTER TABLE "trades" ALTER COLUMN "open_price" TYPE numeric(15,5)`);
        await queryRunner.query(`ALTER TABLE "trades" DROP COLUMN "type"`);
        await queryRunner.query(`ALTER TABLE "trades" ADD "type" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "trades" DROP COLUMN "symbol"`);
        await queryRunner.query(`ALTER TABLE "trades" ADD "symbol" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "trades" DROP COLUMN "account_id"`);
        await queryRunner.query(`ALTER TABLE "trades" ADD "account_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "trades" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "accounts" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "accounts" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL`);
        await queryRunner.query(`ALTER TABLE "accounts" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "accounts" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL`);
        await queryRunner.query(`ALTER TABLE "accounts" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "accounts" ADD "user_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "accounts" DROP CONSTRAINT "UQ_18a4c67cb67bb420271d415b5e1"`);
        await queryRunner.query(`ALTER TABLE "accounts" DROP COLUMN "app_token"`);
        await queryRunner.query(`ALTER TABLE "accounts" ADD "app_token" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "accounts" ADD CONSTRAINT "accounts_app_token_key15" UNIQUE ("app_token")`);
        await queryRunner.query(`ALTER TABLE "accounts" DROP COLUMN "last_seen"`);
        await queryRunner.query(`ALTER TABLE "accounts" ADD "last_seen" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "accounts" ALTER COLUMN "is_connected" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "accounts" ALTER COLUMN "leverage" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "accounts" ALTER COLUMN "margin_level" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "accounts" ALTER COLUMN "margin_free" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "accounts" ALTER COLUMN "margin" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "accounts" ALTER COLUMN "equity" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "accounts" ALTER COLUMN "balance" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "accounts" DROP CONSTRAINT "UQ_bcf86751360dd18bab5efab623a"`);
        await queryRunner.query(`ALTER TABLE "accounts" DROP COLUMN "mt5_id"`);
        await queryRunner.query(`ALTER TABLE "accounts" ADD "mt5_id" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "accounts" ADD CONSTRAINT "accounts_mt5_id_key15" UNIQUE ("mt5_id")`);
        await queryRunner.query(`ALTER TABLE "accounts" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "trades" DROP COLUMN "swap"`);
        await queryRunner.query(`ALTER TABLE "trades" DROP COLUMN "commission"`);
        await queryRunner.query(`DROP TABLE "positions"`);
        await queryRunner.query(`CREATE INDEX "trades_account_id_close_time" ON "trades" ("account_id", "close_time") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "trades_account_id_ticket" ON "trades" ("account_id", "ticket") `);
        await queryRunner.query(`ALTER TABLE "trades" ADD CONSTRAINT "trades_account_id_fkey" FOREIGN KEY ("account_id") REFERENCES "accounts"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "accounts" ADD CONSTRAINT "accounts_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

}
